/*
 * config.h
 *
 * Created: 5/26/2016 10:13:41 AM
 *  Author: nrpic_000
 */ 


#ifndef CONFIG_H_
#define CONFIG_H_

#include "projectHeader.h"

//'System' Class Functions
void configureIO();
void configureExternalOscillator();
void configure32MhzInternalOsc();
void configureTimerCounter();
void configureRTC();
void configureADCs();
void configureXCL();
void configureSerialNumber();
uint8_t ReadCalibrationByte(uint8_t index);
uint8_t ReadSignatureByte(uint16_t Address);

volatile uint8_t broadcastStatus = 0;
volatile uint64_t longCounter = 0;
volatile uint8_t PWMMeasuringStatus = NOT_MEASURING;
volatile uint64_t longTemp = 0;
volatile uint16_t steeringPWMPeriod;		//Contains the steering PWM input period in uS
uint8_t DeviceSignature[11];		//Contains raw device serial number information
uint64_t UC_LOT_NUMBER;		//Contains a number genrated by the lot number
uint64_t UC_WAFER_ID;		//Contains a number generated by the wafer position


#endif /* CONFIG_H_ */