/*
 * main.h
 *
 * Created: 12/30/2015 1:45:45 PM
 *  Author: Nick McComb [nickmccomb.net]
 */ 


#ifndef MAIN_H_
#define MAIN_H_

#include "projectHeader.h"

/* Function Prototypes */

//'User' Class Functions
double getEBoxTemperature();
double getBatteryVoltage(uint8_t batterySelect);
double getSystemCurrent(uint8_t currentSelect);
uint16_t inline getXTendRSSI();

//'System' Class Functions
void inline debuggingOutput();
int16_t sampleTempSensorVoltage(void);
int16_t sampleBatteryVoltage(uint8_t batterySelect);
uint16_t sampleCurrentSensor(uint8_t currentSelect);
double ADCCountToVoltage(uint16_t adcCount);

//EXTERNAL functions (not defined in MAIN)

//config
extern void configureIO();
extern void configureExternalOscillator();
extern void configure32MhzInternalOsc();
extern void configureTimerCounter();
extern void configureRTC();
extern void configureADCs();
extern void configureXCL();
extern void configureUSART();
extern void configureSerialNumber();
extern uint8_t ReadCalibrationByte( uint8_t index );
//usart
extern void SendStringPC(char *stufftosend);
extern void SendStringPC(const char stufftosend[]);
extern void SendCharPC(char charToSend);
extern void SendCharONOFF(char charToSend);
extern void SendNumPC(uint8_t numToSend);
extern void SendNumPC(uint16_t numToSend);
extern void SendNumPC(int16_t numToSend);
extern void SendNumPC(uint64_t numToSend);
extern void SendFloatPC(double numToSend);

/* Global Variables */

extern volatile uint8_t broadcastStatus;
extern volatile uint64_t longCounter;
extern volatile uint64_t longTemp;
extern volatile uint16_t steeringPWMPeriod;
extern uint8_t DeviceSignature[11];
extern uint64_t UC_LOT_NUMBER;		//Contains a number genrated by the lot number
extern uint64_t UC_WAFER_ID;		//Contains a number generated by the wafer position
extern int16_t serialNumber;		//Creates an OMG Custom Serial number, ref. https://goo.gl/15qd7k

/* Main program defines */

#define RSSI_MAX_COUNT 273   //Calculated to have a max of 272.629 (32.768*.00832)
#define STATIC_STATUS_OUTPUT_COUNT 5	//Used to determine how many times thins like "remote output"
										//are outputted before the information "expires"




#endif /* MAIN_H_ */